name: Deploy to FTP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
      
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cozzanifacundo.com
          username: u553004748.devquiz.site
          password: MiPassword123!
          local-dir: ./dist/
          server-dir: ./ 
          log-level: verbose 
